# Generated by Django 5.2.8 on 2025-11-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_ai_question_ai_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('proposed', 'procesed'), ('called', 'called'), ('converted', 'converted'), ('trash', 'trash')], default='proposed', max_length=50),
        ),
    ]
