# Generated by Django 5.2.8 on 2025-11-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('mcq', 'mcq'), ('mic', 'mic')], default='text', max_length=50),
        ),
    ]
