# Generated by Django 5.2.8 on 2025-11-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_question',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
