# Generated by Django 5.2.8 on 2025-12-04 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_question_next_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_question',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.ai_question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_no', 'project_type')},
        ),
    ]
