# Generated by Django 5.2.8 on 2025-12-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_ai_question_next_question_question_question_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_question',
            name='question_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ai_question',
            unique_together={('question_no', 'project')},
        ),
    ]
