# Generated by Django 5.2.9 on 2025-12-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='icon',
            field=models.CharField(default='📁', max_length=10),
        ),
    ]
