# Generated by Django 5.2.9 on 2025-12-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_questions_enabled', models.BooleanField(default=True)),
                ('voice_input_enabled', models.BooleanField(default=False)),
                ('report_regeneration_enabled', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#4f46e5', max_length=20)),
                ('accent_color', models.CharField(default='#10b981', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
