# Generated by Django 5.2.8 on 2025-11-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
